#!/usr/bin/env python3
"""site-search · index generator.

Walks every category section of SERVICES.md and emits site-index.js with one
entry per service: name, category, page, anchor, and canonical pill set.
Reads ONLY service headings (##### Name · *verdict*) and their backtick pill
rows; prose, verdicts, bullets, and footers are never read into the index.

Usage: python3 site-search/build_index.py
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SERVICES = HERE / "SERVICES.md"
OUT = HERE / "site-index.js"

# SERVICES.md "### Category" -> category page. Resources has no service cards.
PAGES = {
    "Browsers & Search": "browsers.html",
    "DNS & Network": "dns.html",
    "VPNs": "vpns.html",
    "Anonymizing Networks": "anonymizing-networks.html",
    "Password Managers": "password-managers.html",
    "2FA & Hardware Keys": "2fa.html",
    "Alias Services": "alias-services.html",
    "Personal Data Removers": "data-removal.html",
    "Messengers": "messaging.html",
    "Email Providers": "email-providers.html",
    "Social Media": "social-media.html",
    "Communities": "communities.html",
    "Frontends": "frontends.html",
    "Cloud Storage & Sync": "cloud-storage.html",
    "Notes": "notes.html",
    "File Sharing": "file-sharing.html",
    "Office Suites": "office-suites.html",
    "Encryption": "encryption.html",
    "Mobile OS": "mobile-os.html",
    "Desktop OS": "desktop-os.html",
    "Financial Services": "financial-services.html",
    "Cellular Services": "cellular.html",
    "AI Tools": "ai-tools.html",
    "Maps": "maps.html",
}

# md heading name -> display name used on the HTML card (and for the anchor).
DISPLAY = {"mailbox (formerly Mailbox.org)": "mailbox"}

# Short dropdown labels for page slugs that are too long for the category tag.
LABELS = {
    "anonymizing-networks": "anonymity",
    "password-managers": "passwords",
    "alias-services": "aliases",
    "data-removal": "removal",
    "email-providers": "email",
    "social-media": "social",
    "communities": "community",
    "cloud-storage": "cloud",
    "file-sharing": "sharing",
    "office-suites": "office",
    "mobile-os": "mobile os",
    "desktop-os": "desktop os",
    "financial-services": "financial",
    "ai-tools": "ai tools",
}


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


lines = SERVICES.read_text(encoding="utf-8").split("\n")
entries = []
category = None
skipped = []

for i, line in enumerate(lines):
    if line.startswith("### "):
        category = line[4:].strip()
        continue
    h = re.match(r"^##### (.+?) · \*(.+?)\*\s*$", line)
    if not h:
        if line.startswith("#####"):
            skipped.append(f"line {i+1}: unparseable heading: {line!r}")
        continue
    if category not in PAGES:
        skipped.append(f"line {i+1}: {h.group(1)!r} outside a mapped category ({category!r})")
        continue

    name = DISPLAY.get(h.group(1).strip(), h.group(1).strip())
    pills = []
    for row in lines[i + 1 :]:
        row = row.strip()
        if row.startswith("#"):
            break
        if row.startswith("`") and row.endswith("`") and len(row) > 1:
            pills = [p.strip() for p in re.findall(r"`([^`]+)`", row) if p.strip()]
            break

    entries.append(
        {
            "name": name,
            "category": LABELS.get(PAGES[category].removesuffix(".html"), PAGES[category].removesuffix(".html")),
            "page": "tools/" + PAGES[category],
            "anchor": slug(name),
            "pills": pills,
        }
    )

if skipped:
    print("build_index: WARNINGS:", *skipped, sep="\n  ", file=sys.stderr)
if not entries:
    sys.exit("build_index: no services parsed")

banner = (
    "// GENERATED by site-search/build_index.py from SERVICES.md (service names\n"
    "// and canonical pill rows only; prose is never indexed). Do not edit by\n"
    "// hand; rerun the build script instead.\n"
)
OUT.write_text(
    banner + "window.SITE_INDEX = " + json.dumps(entries, indent=2, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)

cats = {}
for e in entries:
    cats[e["category"]] = cats.get(e["category"], 0) + 1
print(f"build_index: wrote {len(entries)} services across {len(cats)} categories to {OUT.relative_to(ROOT)}")
for c, n in cats.items():
    print(f"  {c}: {n}")
