// GENERATED by site-search/build_index.py from SERVICES.md (service names
// and canonical pill rows only; prose is never indexed). Do not edit by
// hand; rerun the build script instead.
window.SITE_INDEX = [
  {
    "name": "Brave",
    "category": "browsers",
    "page": "tools/browsers.html",
    "anchor": "brave",
    "pills": [
      "chromium",
      "open source",
      "ad blocking",
      "anti-fingerprinting",
      "free"
    ]
  },
  {
    "name": "Firefox",
    "category": "browsers",
    "page": "tools/browsers.html",
    "anchor": "firefox",
    "pills": [
      "gecko",
      "open source",
      "free"
    ]
  },
  {
    "name": "Helium",
    "category": "browsers",
    "page": "tools/browsers.html",
    "anchor": "helium",
    "pills": [
      "chromium",
      "open source",
      "ad blocking",
      "no account",
      "free"
    ]
  },
  {
    "name": "Mullvad Browser",
    "category": "browsers",
    "page": "tools/browsers.html",
    "anchor": "mullvad-browser",
    "pills": [
      "gecko",
      "anti-fingerprinting",
      "open source",
      "free"
    ]
  },
  {
    "name": "Vivaldi",
    "category": "browsers",
    "page": "tools/browsers.html",
    "anchor": "vivaldi",
    "pills": [
      "chromium",
      "ad blocking",
      "customizable",
      "free"
    ]
  },
  {
    "name": "LibreWolf",
    "category": "browsers",
    "page": "tools/browsers.html",
    "anchor": "librewolf",
    "pills": [
      "gecko",
      "open source",
      "free"
    ]
  },
  {
    "name": "AdGuard DNS",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "adguard-dns",
    "pills": [
      "🇨🇾 cyprus",
      "encrypted dns",
      "ad blocking",
      "free tier"
    ]
  },
  {
    "name": "Mullvad DNS",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "mullvad-dns",
    "pills": [
      "🇸🇪 sweden",
      "encrypted dns",
      "no logs",
      "no account",
      "free"
    ]
  },
  {
    "name": "Quad9",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "quad9",
    "pills": [
      "🇨🇭 switzerland",
      "encrypted dns",
      "no logs",
      "nonprofit",
      "free"
    ]
  },
  {
    "name": "NextDNS",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "nextdns",
    "pills": [
      "🇺🇸 usa",
      "encrypted dns",
      "customizable",
      "free tier"
    ]
  },
  {
    "name": "Self-host",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "self-host",
    "pills": [
      "self-hostable",
      "open source",
      "customizable",
      "ad blocking",
      "free"
    ]
  },
  {
    "name": "ControlD",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "controld",
    "pills": [
      "🇨🇦 canada",
      "encrypted dns",
      "customizable",
      "free tier"
    ]
  },
  {
    "name": "ReThinkDNS",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "rethinkdns",
    "pills": [
      "🇮🇳 india",
      "encrypted dns",
      "partially open source",
      "no account",
      "free tier"
    ]
  },
  {
    "name": "Cloudflare DNS",
    "category": "dns",
    "page": "tools/dns.html",
    "anchor": "cloudflare-dns",
    "pills": [
      "🇺🇸 usa",
      "encrypted dns",
      "audited",
      "partially open source",
      "free"
    ]
  },
  {
    "name": "Proton VPN",
    "category": "vpns",
    "page": "tools/vpns.html",
    "anchor": "proton-vpn",
    "pills": [
      "🇨🇭 switzerland",
      "audited no-logs",
      "open source",
      "free tier"
    ]
  },
  {
    "name": "Mullvad",
    "category": "vpns",
    "page": "tools/vpns.html",
    "anchor": "mullvad",
    "pills": [
      "🇸🇪 sweden",
      "anonymous signup",
      "cash accepted",
      "audited",
      "paid"
    ]
  },
  {
    "name": "Windscribe",
    "category": "vpns",
    "page": "tools/vpns.html",
    "anchor": "windscribe",
    "pills": [
      "🇨🇦 canada",
      "audited no-logs",
      "ad blocking",
      "free tier"
    ]
  },
  {
    "name": "IVPN",
    "category": "vpns",
    "page": "tools/vpns.html",
    "anchor": "ivpn",
    "pills": [
      "🇬🇮 gibraltar",
      "anonymous signup",
      "multihop",
      "audited",
      "paid"
    ]
  },
  {
    "name": "Obscura VPN",
    "category": "vpns",
    "page": "tools/vpns.html",
    "anchor": "obscura-vpn",
    "pills": [
      "multihop",
      "wireguard",
      "audited",
      "paid"
    ]
  },
  {
    "name": "AzireVPN",
    "category": "vpns",
    "page": "tools/vpns.html",
    "anchor": "azirevpn",
    "pills": [
      "🇸🇪 sweden",
      "audited no-logs",
      "ram-only",
      "wireguard",
      "paid"
    ]
  },
  {
    "name": "Tor",
    "category": "anonymity",
    "page": "tools/anonymizing-networks.html",
    "anchor": "tor",
    "pills": [
      "onion-routed",
      "nonprofit",
      "open source",
      "free"
    ]
  },
  {
    "name": "Orbot",
    "category": "anonymity",
    "page": "tools/anonymizing-networks.html",
    "anchor": "orbot",
    "pills": [
      "onion-routed",
      "open source",
      "free"
    ]
  },
  {
    "name": "I2P",
    "category": "anonymity",
    "page": "tools/anonymizing-networks.html",
    "anchor": "i2p",
    "pills": [
      "onion-routed",
      "open source",
      "free"
    ]
  },
  {
    "name": "Snowflake",
    "category": "anonymity",
    "page": "tools/anonymizing-networks.html",
    "anchor": "snowflake",
    "pills": [
      "free"
    ]
  },
  {
    "name": "Lokinet",
    "category": "anonymity",
    "page": "tools/anonymizing-networks.html",
    "anchor": "lokinet",
    "pills": [
      "onion-routed",
      "open source",
      "free"
    ]
  },
  {
    "name": "1Password",
    "category": "passwords",
    "page": "tools/password-managers.html",
    "anchor": "1password",
    "pills": [
      "🇨🇦 canada",
      "closed source",
      "audited",
      "paid"
    ]
  },
  {
    "name": "Bitwarden",
    "category": "passwords",
    "page": "tools/password-managers.html",
    "anchor": "bitwarden",
    "pills": [
      "🇺🇸 usa",
      "open source",
      "audited",
      "self-hostable",
      "free tier"
    ]
  },
  {
    "name": "KeePassXC",
    "category": "passwords",
    "page": "tools/password-managers.html",
    "anchor": "keepassxc",
    "pills": [
      "local-first",
      "open source",
      "no account",
      "totp",
      "free"
    ]
  },
  {
    "name": "Proton Pass",
    "category": "passwords",
    "page": "tools/password-managers.html",
    "anchor": "proton-pass",
    "pills": [
      "🇨🇭 switzerland",
      "partially open source",
      "e2ee",
      "aliasing",
      "free tier"
    ]
  },
  {
    "name": "Dashlane",
    "category": "passwords",
    "page": "tools/password-managers.html",
    "anchor": "dashlane",
    "pills": [
      "🇺🇸 usa",
      "zero-knowledge",
      "closed source",
      "paid"
    ]
  },
  {
    "name": "YubiKey 5 Series",
    "category": "2fa",
    "page": "tools/2fa.html",
    "anchor": "yubikey-5-series",
    "pills": [
      "🇸🇪 sweden",
      "fido2",
      "totp",
      "closed source",
      "paid"
    ]
  },
  {
    "name": "Nitrokey 3",
    "category": "2fa",
    "page": "tools/2fa.html",
    "anchor": "nitrokey-3",
    "pills": [
      "🇩🇪 germany",
      "fido2",
      "totp",
      "open source",
      "paid"
    ]
  },
  {
    "name": "Aegis Authenticator",
    "category": "2fa",
    "page": "tools/2fa.html",
    "anchor": "aegis-authenticator",
    "pills": [
      "android only",
      "totp",
      "open source",
      "local-first",
      "free"
    ]
  },
  {
    "name": "Ente Auth",
    "category": "2fa",
    "page": "tools/2fa.html",
    "anchor": "ente-auth",
    "pills": [
      "totp",
      "open source",
      "e2ee",
      "audited",
      "free"
    ]
  },
  {
    "name": "Proton Auth",
    "category": "2fa",
    "page": "tools/2fa.html",
    "anchor": "proton-auth",
    "pills": [
      "all platforms",
      "totp",
      "open source",
      "e2ee",
      "free"
    ]
  },
  {
    "name": "SimpleLogin",
    "category": "aliases",
    "page": "tools/alias-services.html",
    "anchor": "simplelogin",
    "pills": [
      "open source",
      "self-hostable",
      "reply-from-alias",
      "browser extension",
      "free tier"
    ]
  },
  {
    "name": "Addy.io",
    "category": "aliases",
    "page": "tools/alias-services.html",
    "anchor": "addy-io",
    "pills": [
      "open source",
      "self-hostable",
      "reply-from-alias",
      "browser extension",
      "free tier"
    ]
  },
  {
    "name": "EasyOptOuts",
    "category": "removal",
    "page": "tools/data-removal.html",
    "anchor": "easyoptouts",
    "pills": [
      "paid"
    ]
  },
  {
    "name": "Incogni",
    "category": "removal",
    "page": "tools/data-removal.html",
    "anchor": "incogni",
    "pills": [
      "paid"
    ]
  },
  {
    "name": "DeleteMe",
    "category": "removal",
    "page": "tools/data-removal.html",
    "anchor": "deleteme",
    "pills": [
      "paid"
    ]
  },
  {
    "name": "Signal",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "signal",
    "pills": [
      "🇺🇸 usa",
      "e2ee always",
      "metadata-resistant",
      "open source",
      "free"
    ]
  },
  {
    "name": "iMessage",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "imessage",
    "pills": [
      "🍎 apple only",
      "e2ee optional",
      "closed source",
      "free"
    ]
  },
  {
    "name": "SimpleX",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "simplex",
    "pills": [
      "no identifier required",
      "e2ee always",
      "open source",
      "metadata-resistant",
      "free"
    ]
  },
  {
    "name": "Matrix / Element",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "matrix-element",
    "pills": [
      "federated",
      "e2ee optional",
      "self-hostable",
      "open source",
      "free"
    ]
  },
  {
    "name": "Briar",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "briar",
    "pills": [
      "peer-to-peer",
      "onion-routed",
      "works offline",
      "open source",
      "free"
    ]
  },
  {
    "name": "Threema",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "threema",
    "pills": [
      "🇨🇭 switzerland",
      "no phone number",
      "one-time purchase",
      "partially open source"
    ]
  },
  {
    "name": "Session",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "session",
    "pills": [
      "onion-routed",
      "no phone number",
      "decentralized",
      "open source",
      "free"
    ]
  },
  {
    "name": "Telegram",
    "category": "messaging",
    "page": "tools/messaging.html",
    "anchor": "telegram",
    "pills": [
      "e2ee not default",
      "secret chats only",
      "custom mtproto",
      "cloud-stored history",
      "free"
    ]
  },
  {
    "name": "Proton Mail",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "proton-mail",
    "pills": [
      "🇨🇭 switzerland",
      "zero-knowledge",
      "partially open source",
      "audited",
      "free tier"
    ]
  },
  {
    "name": "mailbox",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "mailbox",
    "pills": [
      "🇩🇪 germany",
      "imap/smtp",
      "pgp",
      "paid"
    ]
  },
  {
    "name": "Tuta",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "tuta",
    "pills": [
      "🇩🇪 germany",
      "post-quantum",
      "open source",
      "free tier"
    ]
  },
  {
    "name": "Posteo",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "posteo",
    "pills": [
      "🇩🇪 germany",
      "anonymous signup",
      "cash accepted",
      "imap/smtp",
      "paid"
    ]
  },
  {
    "name": "StartMail",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "startmail",
    "pills": [
      "🇳🇱 netherlands",
      "aliasing",
      "imap/smtp",
      "pgp",
      "paid"
    ]
  },
  {
    "name": "Disroot",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "disroot",
    "pills": [
      "🇳🇱 netherlands",
      "nonprofit",
      "imap/smtp",
      "free"
    ]
  },
  {
    "name": "GnuPG",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "gnupg",
    "pills": [
      "all platforms",
      "pgp",
      "open source",
      "free"
    ]
  },
  {
    "name": "Gpg4win",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "gpg4win",
    "pills": [
      "windows only",
      "pgp",
      "open source",
      "free"
    ]
  },
  {
    "name": "GPG Suite",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "gpg-suite",
    "pills": [
      "macos only",
      "pgp",
      "free tier"
    ]
  },
  {
    "name": "OpenKeychain",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "openkeychain",
    "pills": [
      "android only",
      "f-droid",
      "pgp",
      "open source",
      "free"
    ]
  },
  {
    "name": "Thunderbird",
    "category": "email",
    "page": "tools/email-providers.html",
    "anchor": "thunderbird",
    "pills": [
      "desktop app",
      "pgp",
      "open source",
      "free"
    ]
  },
  {
    "name": "Mastodon",
    "category": "social",
    "page": "tools/social-media.html",
    "anchor": "mastodon",
    "pills": [
      "federated",
      "no algorithmic feed",
      "open source",
      "free"
    ]
  },
  {
    "name": "Lemmy",
    "category": "social",
    "page": "tools/social-media.html",
    "anchor": "lemmy",
    "pills": [
      "federated",
      "no algorithmic feed",
      "open source",
      "self-hostable",
      "free"
    ]
  },
  {
    "name": "PeerTube",
    "category": "social",
    "page": "tools/social-media.html",
    "anchor": "peertube",
    "pills": [
      "federated",
      "no algorithmic feed",
      "open source",
      "self-hostable",
      "free"
    ]
  },
  {
    "name": "Pixelfed",
    "category": "social",
    "page": "tools/social-media.html",
    "anchor": "pixelfed",
    "pills": [
      "federated",
      "no algorithmic feed",
      "open source",
      "free"
    ]
  },
  {
    "name": "Stoat",
    "category": "community",
    "page": "tools/communities.html",
    "anchor": "stoat",
    "pills": [
      "self-hostable",
      "open source",
      "free"
    ]
  },
  {
    "name": "Fluxer",
    "category": "community",
    "page": "tools/communities.html",
    "anchor": "fluxer",
    "pills": [
      "🇸🇪 sweden",
      "open source",
      "free tier"
    ]
  },
  {
    "name": "LibRedirect",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "libredirect",
    "pills": [
      "browser extension",
      "open source",
      "free"
    ]
  },
  {
    "name": "Redlib",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "redlib",
    "pills": [
      "web-based",
      "self-hostable",
      "open source",
      "free"
    ]
  },
  {
    "name": "Invidious",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "invidious",
    "pills": [
      "web-based",
      "self-hostable",
      "open source",
      "free"
    ]
  },
  {
    "name": "Piped",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "piped",
    "pills": [
      "web-based",
      "self-hostable",
      "open source",
      "free"
    ]
  },
  {
    "name": "FreeTube",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "freetube",
    "pills": [
      "desktop app",
      "local-first",
      "open source",
      "free"
    ]
  },
  {
    "name": "NewPipe",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "newpipe",
    "pills": [
      "android only",
      "f-droid",
      "open source",
      "free"
    ]
  },
  {
    "name": "LibreTube",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "libretube",
    "pills": [
      "android only",
      "f-droid",
      "open source",
      "free"
    ]
  },
  {
    "name": "Nitter",
    "category": "frontends",
    "page": "tools/frontends.html",
    "anchor": "nitter",
    "pills": [
      "web-based",
      "open source",
      "free"
    ]
  },
  {
    "name": "Filen",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "filen",
    "pills": [
      "🇩🇪 germany",
      "zero-knowledge",
      "e2ee",
      "all platforms",
      "free tier"
    ]
  },
  {
    "name": "Tresorit",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "tresorit",
    "pills": [
      "🇨🇭 switzerland",
      "e2ee",
      "audited",
      "free tier"
    ]
  },
  {
    "name": "Syncthing",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "syncthing",
    "pills": [
      "peer-to-peer",
      "open source",
      "no account",
      "free"
    ]
  },
  {
    "name": "Proton Drive",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "proton-drive",
    "pills": [
      "🇨🇭 switzerland",
      "e2ee",
      "free tier"
    ]
  },
  {
    "name": "Cryptomator",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "cryptomator",
    "pills": [
      "e2ee",
      "open source",
      "audited",
      "no account",
      "free tier"
    ]
  },
  {
    "name": "Nextcloud",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "nextcloud",
    "pills": [
      "self-hostable",
      "open source",
      "e2ee optional",
      "free"
    ]
  },
  {
    "name": "pCloud",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "pcloud",
    "pills": [
      "🇨🇭 switzerland",
      "one-time purchase",
      "e2ee optional",
      "free tier"
    ]
  },
  {
    "name": "Mega NZ",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "mega-nz",
    "pills": [
      "e2ee",
      "free tier"
    ]
  },
  {
    "name": "Ente Photos",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "ente-photos",
    "pills": [
      "e2ee",
      "open source",
      "free tier"
    ]
  },
  {
    "name": "IceDrive",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "icedrive",
    "pills": [
      "client-side encryption option",
      "proprietary crypto",
      "not independently audited",
      "cheap"
    ]
  },
  {
    "name": "Internxt",
    "category": "cloud",
    "page": "tools/cloud-storage.html",
    "anchor": "internxt",
    "pills": [
      "🇪🇸 spain",
      "zero-knowledge",
      "post-quantum",
      "audited",
      "free tier"
    ]
  },
  {
    "name": "Notesnook",
    "category": "notes",
    "page": "tools/notes.html",
    "anchor": "notesnook",
    "pills": [
      "e2ee",
      "open source",
      "audited",
      "all platforms",
      "free tier"
    ]
  },
  {
    "name": "Obsidian",
    "category": "notes",
    "page": "tools/notes.html",
    "anchor": "obsidian",
    "pills": [
      "local-first",
      "closed source",
      "free tier"
    ]
  },
  {
    "name": "Standard Notes",
    "category": "notes",
    "page": "tools/notes.html",
    "anchor": "standard-notes",
    "pills": [
      "e2ee",
      "open source",
      "audited",
      "free tier"
    ]
  },
  {
    "name": "Logseq",
    "category": "notes",
    "page": "tools/notes.html",
    "anchor": "logseq",
    "pills": [
      "local-first",
      "open source",
      "free"
    ]
  },
  {
    "name": "Joplin",
    "category": "notes",
    "page": "tools/notes.html",
    "anchor": "joplin",
    "pills": [
      "open source",
      "e2ee optional",
      "local-first",
      "free"
    ]
  },
  {
    "name": "Cryptee",
    "category": "notes",
    "page": "tools/notes.html",
    "anchor": "cryptee",
    "pills": [
      "e2ee",
      "zero-knowledge",
      "web-based",
      "works offline",
      "free tier"
    ]
  },
  {
    "name": "LocalSend",
    "category": "sharing",
    "page": "tools/file-sharing.html",
    "anchor": "localsend",
    "pills": [
      "open source",
      "peer-to-peer",
      "no account",
      "free"
    ]
  },
  {
    "name": "OnionShare",
    "category": "sharing",
    "page": "tools/file-sharing.html",
    "anchor": "onionshare",
    "pills": [
      "open source",
      "onion-routed",
      "no account",
      "free"
    ]
  },
  {
    "name": "Buzzheavier",
    "category": "sharing",
    "page": "tools/file-sharing.html",
    "anchor": "buzzheavier",
    "pills": [
      "web-based",
      "no account",
      "free tier"
    ]
  },
  {
    "name": "PrivateBin",
    "category": "sharing",
    "page": "tools/file-sharing.html",
    "anchor": "privatebin",
    "pills": [
      "open source",
      "zero-knowledge",
      "self-hostable",
      "no account",
      "free"
    ]
  },
  {
    "name": "OnlyOffice",
    "category": "office",
    "page": "tools/office-suites.html",
    "anchor": "onlyoffice",
    "pills": [
      "partially open source",
      "self-hostable",
      "desktop app",
      "free tier"
    ]
  },
  {
    "name": "LibreOffice",
    "category": "office",
    "page": "tools/office-suites.html",
    "anchor": "libreoffice",
    "pills": [
      "open source",
      "local-first",
      "no account",
      "free"
    ]
  },
  {
    "name": "OpenOffice",
    "category": "office",
    "page": "tools/office-suites.html",
    "anchor": "openoffice",
    "pills": [
      "open source",
      "local-first",
      "free"
    ]
  },
  {
    "name": "CryptPad",
    "category": "office",
    "page": "tools/office-suites.html",
    "anchor": "cryptpad",
    "pills": [
      "e2ee",
      "zero-knowledge",
      "real-time collaboration",
      "open source",
      "free tier"
    ]
  },
  {
    "name": "Fileverse",
    "category": "office",
    "page": "tools/office-suites.html",
    "anchor": "fileverse",
    "pills": [
      "decentralized",
      "e2ee",
      "free"
    ]
  },
  {
    "name": "VeraCrypt",
    "category": "encryption",
    "page": "tools/encryption.html",
    "anchor": "veracrypt",
    "pills": [
      "open source",
      "audited",
      "desktop app",
      "hidden volumes",
      "free"
    ]
  },
  {
    "name": "LUKS",
    "category": "encryption",
    "page": "tools/encryption.html",
    "anchor": "luks",
    "pills": [
      "linux only",
      "open source",
      "free"
    ]
  },
  {
    "name": "BitLocker",
    "category": "encryption",
    "page": "tools/encryption.html",
    "anchor": "bitlocker",
    "pills": [
      "windows only",
      "closed source",
      "paid"
    ]
  },
  {
    "name": "iOS",
    "category": "mobile os",
    "page": "tools/mobile-os.html",
    "anchor": "ios",
    "pills": [
      "🍎 apple only",
      "closed source",
      "free"
    ]
  },
  {
    "name": "GrapheneOS",
    "category": "mobile os",
    "page": "tools/mobile-os.html",
    "anchor": "grapheneos",
    "pills": [
      "open source",
      "verified boot",
      "sandboxed play",
      "free"
    ]
  },
  {
    "name": "CalyxOS",
    "category": "mobile os",
    "page": "tools/mobile-os.html",
    "anchor": "calyxos",
    "pills": [
      "open source",
      "nonprofit",
      "free"
    ]
  },
  {
    "name": "LineageOS",
    "category": "mobile os",
    "page": "tools/mobile-os.html",
    "anchor": "lineageos",
    "pills": [
      "open source",
      "free"
    ]
  },
  {
    "name": "Fedora Workstation",
    "category": "desktop os",
    "page": "tools/desktop-os.html",
    "anchor": "fedora-workstation",
    "pills": [
      "open source",
      "free"
    ]
  },
  {
    "name": "Secureblue",
    "category": "desktop os",
    "page": "tools/desktop-os.html",
    "anchor": "secureblue",
    "pills": [
      "immutable",
      "open source",
      "free"
    ]
  },
  {
    "name": "Tails",
    "category": "desktop os",
    "page": "tools/desktop-os.html",
    "anchor": "tails",
    "pills": [
      "amnesic",
      "onion-routed",
      "free"
    ]
  },
  {
    "name": "Qubes OS",
    "category": "desktop os",
    "page": "tools/desktop-os.html",
    "anchor": "qubes-os",
    "pills": [
      "compartmentalized",
      "open source",
      "free"
    ]
  },
  {
    "name": "Arch Linux",
    "category": "desktop os",
    "page": "tools/desktop-os.html",
    "anchor": "arch-linux",
    "pills": [
      "open source",
      "free"
    ]
  },
  {
    "name": "NixOS",
    "category": "desktop os",
    "page": "tools/desktop-os.html",
    "anchor": "nixos",
    "pills": [
      "open source",
      "free"
    ]
  },
  {
    "name": "Privacy.com",
    "category": "financial",
    "page": "tools/financial-services.html",
    "anchor": "privacy-com",
    "pills": [
      "us only",
      "virtual cards",
      "free tier"
    ]
  },
  {
    "name": "MySudo",
    "category": "financial",
    "page": "tools/financial-services.html",
    "anchor": "mysudo",
    "pills": [
      "virtual cards",
      "aliasing",
      "paid"
    ]
  },
  {
    "name": "Cape",
    "category": "cellular",
    "page": "tools/cellular.html",
    "anchor": "cape",
    "pills": [
      "us only",
      "mvno",
      "minimal data collection",
      "paid"
    ]
  },
  {
    "name": "Phreeli",
    "category": "cellular",
    "page": "tools/cellular.html",
    "anchor": "phreeli",
    "pills": [
      "mvno",
      "minimal data collection",
      "paid"
    ]
  },
  {
    "name": "Silent Link",
    "category": "cellular",
    "page": "tools/cellular.html",
    "anchor": "silent-link",
    "pills": [
      "esim only",
      "anonymous signup",
      "crypto accepted",
      "paid"
    ]
  },
  {
    "name": "Saily",
    "category": "cellular",
    "page": "tools/cellular.html",
    "anchor": "saily",
    "pills": [
      "esim only",
      "paid"
    ]
  },
  {
    "name": "Duck.ai",
    "category": "ai tools",
    "page": "tools/ai-tools.html",
    "anchor": "duck-ai",
    "pills": [
      "cloud",
      "no account",
      "free"
    ]
  },
  {
    "name": "Le Chat",
    "category": "ai tools",
    "page": "tools/ai-tools.html",
    "anchor": "le-chat",
    "pills": [
      "cloud",
      "🇫🇷 france",
      "free tier"
    ]
  },
  {
    "name": "Lumo",
    "category": "ai tools",
    "page": "tools/ai-tools.html",
    "anchor": "lumo",
    "pills": [
      "cloud",
      "zero-knowledge",
      "free tier"
    ]
  },
  {
    "name": "Venice AI",
    "category": "ai tools",
    "page": "tools/ai-tools.html",
    "anchor": "venice-ai",
    "pills": [
      "cloud",
      "no logs",
      "crypto accepted",
      "free tier"
    ]
  },
  {
    "name": "Ollama",
    "category": "ai tools",
    "page": "tools/ai-tools.html",
    "anchor": "ollama",
    "pills": [
      "local-first",
      "works offline",
      "no account",
      "free"
    ]
  },
  {
    "name": "Apple Maps",
    "category": "maps",
    "page": "tools/maps.html",
    "anchor": "apple-maps",
    "pills": [
      "🍎 apple only",
      "closed source",
      "free"
    ]
  },
  {
    "name": "CoMaps",
    "category": "maps",
    "page": "tools/maps.html",
    "anchor": "comaps",
    "pills": [
      "open source",
      "openstreetmap",
      "no account",
      "works offline",
      "free"
    ]
  },
  {
    "name": "OsmAnd",
    "category": "maps",
    "page": "tools/maps.html",
    "anchor": "osmand",
    "pills": [
      "open source",
      "openstreetmap",
      "works offline",
      "no account",
      "free tier"
    ]
  },
  {
    "name": "Magic Earth",
    "category": "maps",
    "page": "tools/maps.html",
    "anchor": "magic-earth",
    "pills": [
      "closed source",
      "no account",
      "free tier"
    ]
  },
  {
    "name": "Kagi Maps",
    "category": "maps",
    "page": "tools/maps.html",
    "anchor": "kagi-maps",
    "pills": [
      "free"
    ]
  }
];
